apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://192.168.21.100:6443 # est l'adresse du control-plane
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3SGhjTk1qWXdNekkyTWpBek5URTFXaGNOTXpZd016SXpNakF6TlRFMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU5UY3pNVFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ2tIaU1memtTVEI5RWZ6WWVRSzNhMjA1NytRSVFacGxhdGpiZmZlUWIKYytuK2FGc3hnWmI3ckFiRlR4WU40cnN4MlRJRVVKcFExQVlicmtYRHdad1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlkUXl6RmVsTHAwSzBHZDAzdnNSCmVIUmp1dWt3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQXB2bFRSMkorWkFmRXJzK2wzWHZZbjREckliV1V5dzAKWjlocGFUT1llVUVDSUU3WlhLOGZIRm44OWlRSkpIenF6T2YyUm81NU1rV09rZkZqTkVMRUZhQUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ino5NUJFRXNvNmdUcjYtV2ZMdF9tVDZuSnRXNUVmR3FSN0pjRUZvbC1CdlkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc1ODUzMjkzLCJpYXQiOjE3NzU4NDk2OTMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNjI1NTZhMjctNWFhMi00ZjQ1LWJlOTEtOTg3Y2JiMmFlYTllIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6IjY1M2Y3NWExLTEzOWUtNGM2ZS05NWQ4LTg3M2U1NzMzNmY1MyJ9fSwibmJmIjoxNzc1ODQ5NjkzLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.fRjMfuo3VGP5pMdhmJNb3lyEBNPrAhiU7cdoQSdO2o9LywFUvVxKjs1xMegi9skBXBbvUCBtZ-7v0SSeZmDWiIhKMIaaJ3qogp8AE1zGgORlMSSTydTbsGNxOTVte6T9QU3lSQz3m_20y4YNwVbQuRgpf6Hg15fxMITSlAx7V-r5rbBHclvHCSqasLa0UwD_TzHISCOcqw3ePh1PnoeMkV5f6JhdiaaT2oTLGo-g6pEjfgTL9YboJ52a8LhVtndpLCqUtUf5E5k8e2a-CozLbbWhjhWCmLQSUSIGoQuyVVDvR6eESOlG65V3ltN8_4dnY_TXKgLydZ6lSOuj33MAsA

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context